package:
  name: postgresadapter
  version: "2.0.0"

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python 
    - numpy
    - cython
    - postgresql

  run:
    - python 
    - numpy
    - pandas
    - six
    - ordereddict     [py26]
    - libpq

test:
  requires:
    - nose
    - pytest
    - sqlalchemy
    - psycopg2

  imports:
    - postgresadapter
    - postgresadapter.core
    - postgresadapter.core.PostgresAdapter

about:
  home: http://www.continuum.io/
  license: BSD
  summary: python interface for PostgreSQL databases
